# Generated by Django 4.0.4 on 2024-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_category_alter_recipe_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='photo_video',
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipes/videos/'),
        ),
    ]
