# Generated by Django 4.0.4 on 2024-08-03 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_remove_recipe_category_alter_recipe_total_time'),
        ('interactions', '0002_rename_uid_rating_user_remove_rating_post_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('recipe', 'user')},
        ),
    ]
