# Generated by Django 4.0.4 on 2024-08-07 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_category_alter_recipe_total_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0003_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('recipe', 'user')},
        ),
    ]
