# Generated by Django 4.0.4 on 2024-08-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_comments_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
